### ISSUE TITLE
Allow use of testnet/mainnet through .env configuration

### ISSUE THREAD

**Issue by gregscullard** [LimeChain/HCS-Integration-Node#18]
The solution is hard coded to use testnet only, suggest a flag is added to .env to enable easy switching between testnet and main net.

**Comment by gregscullard** [comment]
Also the create topic feature is called `createTestnetTopic`, it probably shouldn't be specific.

**Comment by Perseverance** [comment]
Great suggestions @gregscullard . Will put them in the internal backlog ;)
